### ISSUE TITLE
请问是在什么环境下部署的？

### ISSUE THREAD

**Issue by hardy4yooz** [guomaoqiu/flask_kubernetes#1]
使用的minikube还是集群环境？

**Comment by guomaoqiu** [comment]
> 使用的minikube还是集群环境？
二进制安装方式 k8s集群~

**Comment by hardy4yooz** [comment]
> > 使用的minikube还是集群环境？
> > 二进制安装方式 k8s集群~

有没有比较好的练习环境推荐？谢谢。

**Comment by guomaoqiu** [comment]
> > > 使用的minikube还是集群环境？
> > > 二进制安装方式 k8s集群~
> 
> 有没有比较好的练习环境推荐？谢谢。

官网
